const {
  REACT_APP_AUTHORIZATION,
  REACT_APP_GRAPHQL_ENDPOINT,
  REACT_APP_HOST_URI,
  AEM_AUTHORIZATION,
  AEM_GRAPHQL_ENDPOINT,
  AEM_HOST_URI
} = process.env;


module.exports = {
  AEM_GRAPHQL_ENDPOINT: AEM_GRAPHQL_ENDPOINT || REACT_APP_GRAPHQL_ENDPOINT,
  AEM_AUTHORIZATION: AEM_AUTHORIZATION || REACT_APP_AUTHORIZATION,
  AEM_HOST_URI: AEM_HOST_URI || REACT_APP_HOST_URI
};
